### ISSUE TITLE
problem with copyresource at install

### ISSUE THREAD

**Issue by digitalap3** [mulder21c/hexo-theme-amorfati#1]
```
> hexo-theme-amorfati@1.0.0 postinstall /home/nodeuser/digapoth/themes/amorfati
> npm run copyresource


> hexo-theme-amorfati@1.0.0 copyresource /home/nodeuser/digapoth/themes/amorfati
> copy-resource.sh

sh: 1: copy-resource.sh: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! hexo-theme-amorfati@1.0.0 copyresource: `copy-resource.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the hexo-theme-amorfati@1.0.0 copyresource script.

```
I'm getting the above error on `npm install` in the amorfati dir.  The file is there and it will run with `sh copy-resource.sh`.

However the theme will not run when I run the server so I assume just running it outside npm is not enough.

**Comment by digitalap3** [comment]
When I run `hexo server` I get:
```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: ENOSPC: System limit for number of file watchers reached, watch '/home/nodeuser/digapoth/themes/amorfati/node_modules/core-js-pure/features/weak-set/index.js'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1274:11)
    at createFsWatchInstance (/home/nodeuser/digapoth/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nodeuser/digapoth/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nodeuser/digapoth/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/nodeuser/digapoth/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/nodeuser/digapoth/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqCallback.oncomplete (fs.js:159:5)
```

**Comment by mulder21c** [comment]
@digitalap3 
Can I know the environment you tried?

**Comment by mulder21c** [comment]
@digitalap3 
I've tested it on OSX and found a problem that `sh` does not work.
I will try to fix this, but first I want to suggest what you can do.

1. Change mode of `copy-resource.sh`

    ```bash
    $ chmod 755 copy-reousrce.sh
    ```

2. fix package.json

    ```json
    "scripts": {
        "preinstall": "cd ../../ && npm install --save-dev hexo-renderer-jade",
        "test": "echo \"Error: no test specified\" && exit 1",
        "copyresource": "./copy-resource.sh",
        "postinstall": "npm run copyresource"
    },
    ```

3. then, run install

    ```bash
    $ npm install
    ````


The second problem is not reproduced, so it is not confirmed. I will try to do a little more testing, and if it finds the same problem, I will let you know.

**Comment by digitalap3** [comment]
I will try this later, thank you for the reply.  I am running on Debian Stretch using the nvm method of install of node so permissions could be an issue, though I did double check that the file was owned by me. 

I'll let you know the result.

**Comment by digitalap3** [comment]
fixing the syntax of the package.json definitely fixed the install.  However I still get the same error message when trying to run hexo server.  Thank you and let me know if you need any info.

**Comment by mulder21c** [comment]
@digitalap3 That's a good thing. I think I will be able to modify the npm script so that npm scripts can run across various OS soon.

The second problem was not reproduced by me, but I found something that would help with HEXO's official document.

> You can try to run the following command to increase the number of allowed synchronous I/O 
> operations.
> 
>  ```bash
>  $ unlimit -n 10000
>  ```

I hope this will help you solve your problem.

**Comment by digitalap3** [comment]
Cool I'll try it out and let you know.  I forgot to mention I'm working inside a docker container so something like that could be an issue.  I will wipe and start with a fresh container to make sure it reproduces in a more vanilla environment as well.   Or better yet just for the heck of it I'll try in a virtualbox machine.  If that changes anything I will let you know. 

Thank you for the reply and your beautiful theme!
